### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by seonhoshin** [seonhoshin/github_test#2]
### 만들고자 하는 기능이 무엇인가요?
github_test 프로젝트 생성 및 GitHub와 Project간 연동

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] 프로젝트 생성
2. [x] 프로젝트와 Git Repository 연동
3. [x] Controller 기능 테스트
4. [x] 인텔리제이에서 Commit and Push
5. [x] GitHub Repository에서 파일 확인
6. [x] dev 브랜치 생성
7. [x] 인텔리제이에서 dev 브랜치로 checkout
8. [x] 파일 수정
9. [x] 인텔리제이에서 commit and Push
10. [x] GitHub의 origin/dev에서 push 파일 확인
11. [x] 인텔리제이에서 main 브랜치로 checkout. 이후 origin/dev에서 origin/main으로 merge 진행
12. [x] main 브랜치의 파일이 dev 파일처럼 바뀌었는지 확인.
13. [x] origin/main으로 push
